/**
 * AI Generated Badge Component
 * Feature #1787: Extract test list components from TestSuitePage
 * Feature #1164: AI confidence level display
 * Feature #1151: Human review workflow badges
 * Feature #111: Wrapped with React.memo for performance
 */

import { memo } from 'react';
import { AIBadgeProps } from './types';

export const AIBadge = memo(function AIBadge({ isAiGenerated, confidenceScore, reviewStatus }: AIBadgeProps) {
 if (!isAiGenerated) return null;

 const getConfidenceColor = (score: number) => {
 if (score >= 80) return 'text-green-600';
 if (score >= 60) return 'text-yellow-600';
 return 'text-orange-600';
 };

 const getConfidenceTooltip = (score: number) => {
 if (score >= 80) return 'High confidence: Ready for use';
 if (score >= 60) return 'Medium confidence: Review recommended';
 return 'Low confidence: Human review required';
 };

 return (
 <div className="flex items-center gap-1">
 {/* AI Generated Badge */}
 <span
 className="rounded-full px-2 py-0.5 text-xs font-medium bg-purple-100 text-purple-700 cursor-help"
 title={
 confidenceScore !== undefined
 ? `AI Generated - ${confidenceScore}% confidence\n${getConfidenceTooltip(confidenceScore)}`
 : 'This test was generated by AI'
 }
 >
 🤖 AI Generated
 {confidenceScore !== undefined && (
 <span className={`ml-1 font-semibold ${getConfidenceColor(confidenceScore)}`}>
 {confidenceScore}%
 </span>
 )}
 </span>

 {/* Review Status Badges */}
 {reviewStatus === 'pending_review' && (
 <span
 className="rounded-full px-2 py-0.5 text-xs font-medium bg-orange-100 text-orange-700"
 title="Pending human review"
 >
 ⏳ Review
 </span>
 )}
 {reviewStatus === 'approved' && (
 <span
 className="rounded-full px-2 py-0.5 text-xs font-medium bg-blue-100 text-blue-700"
 title="Approved by reviewer"
 >
 ✅ Approved
 </span>
 )}
 {reviewStatus === 'rejected' && (
 <span
 className="rounded-full px-2 py-0.5 text-xs font-medium bg-red-100 text-red-700"
 title="Rejected by reviewer"
 >
 ❌ Rejected
 </span>
 )}
 </div>
 );
});

export default AIBadge;
